package es.manabe.yomiyasu.core.services

import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import es.manabe.yomiyasu.core.models.DictionaryGloss
import es.manabe.yomiyasu.core.models.DictionaryKanji
import es.manabe.yomiyasu.core.models.DictionaryKana
import es.manabe.yomiyasu.core.models.DictionaryPitch
import es.manabe.yomiyasu.core.models.DictionarySense
import es.manabe.yomiyasu.core.models.DictionaryWord
import es.manabe.yomiyasu.core.networking.YomiyasuJson
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.builtins.serializer
import java.io.File

/** Android SQLite adapter for the schema generated by tools/dictionary. */
class AndroidLocalDictionaryDataSource private constructor(
    private val database: SQLiteDatabase,
) : LocalDictionaryDataSource {

    companion object {
        fun open(file: File): AndroidLocalDictionaryDataSource =
            AndroidLocalDictionaryDataSource(
                SQLiteDatabase.openDatabase(
                    file.absolutePath,
                    null,
                    SQLiteDatabase.OPEN_READONLY or SQLiteDatabase.NO_LOCALIZED_COLLATORS,
                ),
            )
    }

    override fun metadata(): Map<String, String> = buildMap {
        database.rawQuery("SELECT key, value FROM metadata ORDER BY key", null).use { cursor ->
            while (cursor.moveToNext()) {
                put(cursor.getString(0), cursor.getString(1))
            }
        }
    }

    override fun lookup(
        kind: String,
        prefix: String,
        limit: Int,
    ): List<LocalDictionaryLookupRow> {
        require(limit > 0) { "limit must be positive" }
        val rows = mutableListOf<LocalDictionaryLookupRow>()
        val upperBound = prefix + "\uDBFF\uDFFF"
        // This is the same range query emitted by the Phase A generator. All
        // user text is bound as an argument; the index hint prevents a full
        // scan and keeps the prefix semantics explicit.
        val sql = """
            SELECT entry_id, source_id, term
            FROM lookup INDEXED BY lookup_prefix_idx
            WHERE kind = ? AND term >= ? AND term < ?
            ORDER BY term, entry_id, source_id
            LIMIT ?
        """.trimIndent()

        database.rawQuery(
            sql,
            arrayOf(kind, prefix, upperBound, limit.toString()),
        ).use { cursor ->
            while (cursor.moveToNext()) {
                rows += LocalDictionaryLookupRow(
                    entryId = cursor.getString(0),
                    sourceId = cursor.getLong(1),
                    term = cursor.getString(2),
                )
            }
        }
        return rows
    }

    override fun readEntry(entryId: String): DictionaryWord? {
        val exists = database.rawQuery(
            "SELECT id FROM entries WHERE id = ? LIMIT 1",
            arrayOf(entryId),
        ).use { it.moveToFirst() }
        if (!exists) return null

        val kanji = mutableListOf<DictionaryKanji>()
        database.rawQuery(
            "SELECT common, text, tags_json FROM kanji WHERE entry_id = ? ORDER BY ordinal",
            arrayOf(entryId),
        ).use { cursor ->
            while (cursor.moveToNext()) {
                kanji += DictionaryKanji(
                    common = cursor.getInt(0) != 0,
                    text = cursor.getString(1),
                    tags = parseStringList(cursor.getString(2)),
                )
            }
        }

        val kana = mutableListOf<DictionaryKana>()
        database.rawQuery(
            """
                SELECT common, text, tags_json, applies_to_kanji_json
                FROM readings WHERE entry_id = ? ORDER BY ordinal
            """.trimIndent(),
            arrayOf(entryId),
        ).use { cursor ->
            while (cursor.moveToNext()) {
                kana += DictionaryKana(
                    common = cursor.getInt(0) != 0,
                    text = cursor.getString(1),
                    tags = parseStringList(cursor.getString(2)),
                    appliesToKanji = parseStringList(cursor.getString(3)),
                )
            }
        }

        val senses = mutableListOf<DictionarySense>()
        database.rawQuery(
            """
                SELECT id, part_of_speech_json, applies_to_kanji_json,
                       applies_to_kana_json, misc_json
                FROM senses WHERE entry_id = ? ORDER BY ordinal
            """.trimIndent(),
            arrayOf(entryId),
        ).use { cursor ->
            while (cursor.moveToNext()) {
                val senseId = cursor.getLong(0)
                val gloss = mutableListOf<DictionaryGloss>()
                database.rawQuery(
                    """
                        SELECT lang, text FROM glosses
                        WHERE sense_id = ? ORDER BY ordinal
                    """.trimIndent(),
                    arrayOf(senseId.toString()),
                ).use { glossCursor ->
                    while (glossCursor.moveToNext()) {
                        gloss += DictionaryGloss(
                            lang = glossCursor.getString(0),
                            text = glossCursor.getString(1),
                        )
                    }
                }

                senses += DictionarySense(
                    partOfSpeech = parseStringList(cursor.getString(1)),
                    appliesToKanji = parseStringList(cursor.getString(2)),
                    appliesToKana = parseStringList(cursor.getString(3)),
                    misc = parseStringList(cursor.getString(4)),
                    gloss = gloss,
                )
            }
        }

        val firstReading = kana.firstOrNull()?.text.orEmpty()
        val frequency = readOptionalFrequency(entryId, firstReading)
        val pitches = readOptionalPitches(entryId)

        return DictionaryWord(
            id = entryId,
            frequency = frequency,
            pitches = pitches,
            kanji = kanji,
            kana = kana,
            sense = senses,
        )
    }

    private fun readOptionalFrequency(entryId: String, reading: String): String? = runCatching {
        database.rawQuery(
            """
                SELECT rank FROM frequency
                WHERE entry_id = ? AND (reading = ? OR reading = '')
                ORDER BY id LIMIT 1
            """.trimIndent(),
            arrayOf(entryId, reading),
        ).use { cursor ->
            if (cursor.moveToFirst()) cursor.getString(0) else null
        }
    }.getOrNull()

    private fun readOptionalPitches(entryId: String): List<DictionaryPitch>? = runCatching {
        val result = mutableListOf<DictionaryPitch>()
        database.rawQuery(
            "SELECT position FROM pitch WHERE entry_id = ? ORDER BY id",
            arrayOf(entryId),
        ).use { cursor ->
            while (cursor.moveToNext()) result += DictionaryPitch(cursor.getInt(0))
        }
        result.takeIf { it.isNotEmpty() }
    }.getOrNull()

    private fun parseStringList(value: String): List<String> =
        YomiyasuJson.decodeFromString(ListSerializer(String.serializer()), value)

    override fun close() {
        database.close()
    }
}

private inline fun <T> Cursor.use(block: (Cursor) -> T): T =
    try {
        block(this)
    } finally {
        close()
    }
